acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail<bpk>/', views.detail, name="detail")
]

vote/models.py
from django.db import models
from acc.models import User
# Create your models here.

class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")

    def __str__(self):
        return self.subject

class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.topic}_{self.name}"

vote/views.py
from django.shortcuts import render
from .models import vote 
# Create your views here.
def index(request):
    t = Topic.objects.all()
    c = Choice.objects.all()
    context = {
        "tset" : t
    }
    context = {
        "cset" : c
    }
    return render(request, "vote/index.html", context)

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>{{ t.subject }}</b></h1>
    
    <form>
        <div>
            <div class="row mt-4">
                <div class="col-sm-8">
                    <textarea class="form-control" disabled style="height: 200px;">{{ t.content }}</textarea>
                </div>
            </div>
            <div calss="col-sm-4">
                <img src="{{ t.maker.getpic }}" width="100%">
                <div class="text-ceneter mt-3"><b>{{ t.maker }}</b></div>
            </div>
        </div>


        <form method="post" action="{% url 'vote:vote' t.id %}"
        {{% csrf_token %}}
        <div class="row mt-4">
            <div class="col-sm-4">
                <input type="radio"> 선택지 이름
                <textarea class="form-control mt-3" style="height: 100px;" disabled></textarea>
            </div>
        </div>
    </form>

{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>투표소</b></h1>
    
{% endblock %}