acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser): # AbstractBaseUser 아니에요
    pic = models.ImageField(upload_to="user")
    comment = models.TextField()
    point = models.IntegerField(default=0)

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import check_password
from acc.models import User
# Create your views here.

def chpass(request):
    cp = request.POST.get("cpass")
    if check_password(cp, request.user.password):
        np = request.POST.get("npass")
        request.user.set_password(np)
        request.user.save()
        return redirect("acc:login")
    return redirect("acc:update") 

def update(request):
    if request.method == "POST":
        u = request.user
        up = request.FILES.get("upic")
        uc = request.POST.get("ucomm")
        um = request.POST.get("umail")
        if up:
            u.pic = up
        u.email = um
        u.comment = uc
        u.save()
        return redirect("acc:profile")
    return render(request, "acc/update.html")


def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("ucomm")
        pi = request.FILES.get("upic")
        User.objects.create_user(username=un, password=up,
        comment=uc, pic=pi)
        return redirect("acc:login")
    return render(request, "acc/signup.html")


def delete(request):
    pw = request.POST.get("pwck")
    if check_password(pw, request.user.password):
        request.user.pic.delete()
        request.user.delete()
        return redirect("acc:index")
    return redirect("acc:profile")

def profile(request):
    return render(request, "acc/profile.html")

def userlogout(request):
    logout(request)
    return redirect("acc:login")

def userlogin(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un,password=up)
        if u:
            login(request, u)
            return redirect("acc:index")
        else:
            pass
    return render(request, "acc/login.html")

def index(request):
    return render(request, "acc/index.html")

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}

    {% if user.is_authenticated %}
        <h4>{{user}}! HAVE A NICE DAY :)</h4>
    {% else %}
        <h4>LOGIN FIRST!</h4>
    {% endif %}

{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block con %}

    <h1><b>LOGIN PAGE</b></h1>

    <form method="post">
        {% csrf_token %}
        <input type="text" class="form-control mt-5" name="uname" placeholder="INPUT USERNAME">
        <input type="password" class="form-control mt-4" name="upass" placeholder="INPUT PASSWORD">
        <div class="text-end mt-4">
            <button class="btn btn-dark">로그인</button>
        </div>
    </form>


{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>USER 프로필</b></h1>


    <div class="row">
        <div class="col-sm-4 text-center" style="margin: auto;">
            <img src="{{user.getpic}}" width="90%">
        </div>
        <div class="col-sm-8">
            <b>USERNAME</b>
            <input type="text" value="{{ user }}" class="form-control mt-3 mb-4" disabled>
            <b>POINT</b>
            <input type="text" value="{{ user.point }} P" class="form-control mt-3 mb-4" disabled>
            <b>EMAIL</b>
            <input type="text" value="{{ user.email }}" class="form-control mt-3 mb-4" disabled>
        </div>
    </div>

    <textarea class="form-control mt-2" style="height: 180px;" disabled>{{user.comment}}</textarea>

    <div class="text-end mt-4">
        <a href="{% url 'acc:update' %}"><button class="btn btn-secondary">프로필수정</button></a>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            계정삭제
        </button>
    </div>


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">계정삭제 알림창</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <form method="post" action="{% url 'acc:delete' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <b>패스워드 확인</b>
                        <input type="password" name="pwck" class="form-control mt-3" placeholder="INPUT PASSWORD">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-danger">삭제</button>
                    </div> 
                </form>
            </div>
        </div>
      </div>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>회원가입</b></h1>

    <form name="registForm" method="post" class="mt-5" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME">
        <input type="password" name="upass" class="form-control mt-4 mb-4" placeholder="INPUT PASSWORD">
        <input type="file" name="upic" class="form-control">
        <textarea cols="50" rows="5"  class="form-control mt-5" name="ucomm" placeholder="INPUT COMMENT"></textarea>
        <div class="text-end mt-5">
            <button type="button" onclick="check()" class="btn btn-success">회원가입</button>
        </div> 
    </form>
    <script>
        function check(){
            rf = document.registForm;
            if (!rf.uname.value){
                alert("유저네임을 입력하세요");
            }else if(!rf.upass.value){
                alert("패스워드를 입력하세요");
            }else if(rf.ucomm.value.length < 5){
                alert("자기소개는 5자이상...");
            }else{
                rf.submit();
            }
        }
    </script>

{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>프로필 수정</b></h1>

    <form method="post" class="mt-5" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="uname" class="form-control" value="{{user}}" disabled>
        <input type="email" name="umail" class="form-control mt-4 mb-4" value="{{ user.email }}">
        <input type="file" name="upic" class="form-control">
        <textarea cols="50" rows="5"  class="form-control mt-4" name="ucomm">{{ user.comment }}</textarea>
        <div class="text-end mt-5">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                패스워드변경
            </button>
            <button class="btn btn-success">수정완료</button>
        </div> 
    </form>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">패스워드 변경창</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:chpass' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <input class="form-control mt-3 mb-3" type="password" name="cpass" placeholder="INPUT CURRENT PASSWORD">
                        <input class="form-control mb-3" type="password" name="npass" placeholder="INPUT NEW PASSWORD">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">변경</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}